# Generated by Django 4.2.23 on 2025-09-11 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'ordering': ['market_cap_rank', 'name'], 'verbose_name': 'Cryptocurrency', 'verbose_name_plural': 'Cryptocurrencies'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorite cryptocurrency', 'verbose_name_plural': 'Favorite cryptocurrencies'},
        ),
        migrations.AddField(
            model_name='crypto',
            name='coin_id',
            field=models.CharField(blank=True, help_text="ID from CoinGecko API (e.g., 'bitcoin')", max_length=100, null=True, unique=True, verbose_name='CoinGecko ID'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='market_cap_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Market Cap Rank'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Added at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='notes',
            field=models.TextField(blank=True, help_text='Personal notes about this cryptocurrency', null=True, verbose_name='User notes'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Price in USD'),
        ),
    ]
