# Generated by Django 4.2.23 on 2025-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecrypto',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='favoritecrypto',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
