# Generated by Django 4.2.23 on 2025-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favoritecrypto_image_url_favoritecrypto_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecrypto',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
